services:
  favo-postgres-16:
    container_name: favo-postgres-16
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vJs0_yJMuDN57gdhiYojOZm8Gn0HvhOx}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: ${TZ:-America/Sao_Paulo}
    ports:
      - "127.0.0.1:5436:5432"
    volumes:
      - favo_postgres16_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - colegio_favo_net

volumes:
  favo_postgres16_data:
    name: favo_postgres16_data

networks:
  colegio_favo_net:
    name: colegio_favo_net
    driver: bridge
